package com.code.httpserver.http;

public enum HttpStatusCodes {
    //CLIENT ERRORS
    CLIENT_ERROR_400_BAD_REQUEST(400,"BAD REQUEST"),
    CLIENT_ERROR_401_METHOD_NOT_ALLOWED(401,"MESSAGE NOT ALLOWED"),
    CLIENT_ERROR_414_BAD_REQUEST(414,"URI TOO LONG"),
    //SERVER ERRORS

    SERVER_ERROR_500_INTERNAL_SERVER_ERROR(500,"INTERNAL SERVER ERROR"),
    SERVER_ERROR_501_NOT_IMPLEMENTED(501,"NOT IMPLEMENTED"),
    SERVER_ERROR_505_HTTP_VERSION_NOT_SUPPORTED(505,"HTTP VERSION NOT SUPPORTED");
    public final int STATUS_CODE;
    public final String MESSAGE;

    HttpStatusCodes(int STATUS_CODE,String MESSAGE){
        this.MESSAGE=MESSAGE;
        this.STATUS_CODE=STATUS_CODE;
    }
}
